### PR TITLE
Change the package name to be npm.js compliant

### PR DESCRIPTION
**Pull request by almet**

### CODE REVIEW

**Comment by maxime-beguin** [comment]
Thanks for the suggestion but we are using NPM organizations that why all openveo projects are under [@openveo](https://www.npmjs.com/~openveo) organization.

**Comment by almet** [comment]
How can I make it work then? Locally when I do "npm install" I'm having an error otherwise:

>  Error: Invalid name: "@openveo/player"

**Comment by maxime-beguin** [comment]
You can install openveo-player using `npm install @openveo/player` or `bower install openveo-player`

**Comment by almet** [comment]
I'm sorry but this doesn't work. What version of npm are you using?

**Comment by maxime-beguin** [comment]
You're right, bower.json was missing in the NPM package and a `bower install` was launched on package postinstall which crashed the installation. I just made a new release of the player (2.0.3) to correct the problem. `npm install @openveo/player` works now. You will need NPM 2.5.0 or greater.

**Pull request closed without merging**
